name: CI test
on:
  push:
    branches: [ "5.13" ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: fribdaq/frib-buster-ci:v3.7
      options: --cpus 1
    steps:
      - uses: actions/checkout@v3
      - name: autoreconf
        working-directory: ./main
        run: autoreconf -if
      - name: Configure tclc++ and unifiedformat
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        working-directory: ./main
        shell: bash
        run: |
          source /usr/local/bin/thisroot.sh
          git config --global --add safe.directory '*'

          eval `ssh-agent -s`
          echo "${{ secrets.PRIVATE_KEY }}" | ssh-add -
          ./tcl++incorp libtclplus-v4.3-002
          ./unifiedfmt-incorp.sh
          ssh-add -D
          
          eval `ssh-agent -k`
      - name: Creating build directory
        run: mkdir main/oot
      - name: Configuring
        working-directory: ./main/oot
        run: ../configure --prefix=$PWD/install
      - name: Make
        working-directory: ./main/oot
        run: make clean && make all && make install
